/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'music' : null } |
  { 'documentary' : null } |
  { 'kids' : null } |
  { 'news' : null } |
  { 'sports' : null } |
  { 'movies' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Channel {
  'id' : ChannelId,
  'name' : string,
  'description' : string,
  'isLive' : boolean,
  'logoUrl' : string,
  'category' : Category,
  'streamUrl' : string,
  'popularity' : bigint,
}
export interface ChannelDetail {
  'nowPlaying' : [] | [Program],
  'upNext' : [] | [Program],
  'channel' : Channel,
}
export type ChannelId = bigint;
export type ChannelSort = { 'name' : null } |
  { 'popularity' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Program {
  'id' : ProgramId,
  'startTime' : Timestamp,
  'title' : string,
  'channelId' : ChannelId,
  'endTime' : Timestamp,
  'description' : string,
}
export type ProgramId = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add a channel to the caller's favorites. Requires a signed-in caller.
   */
  'addFavorite' : ActorMethod<[ChannelId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the backend API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a single channel by id.
   */
  'getChannel' : ActorMethod<[ChannelId], [] | [Channel]>,
  /**
   * / Get a channel with its now-playing and up-next programs.
   */
  'getChannelDetail' : ActorMethod<[ChannelId], [] | [ChannelDetail]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List every channel in the catalog.
   */
  'listChannels' : ActorMethod<[], Array<Channel>>,
  /**
   * / List channels in a category, ordered by the given sort.
   */
  'listChannelsByCategory' : ActorMethod<
    [Category, ChannelSort],
    Array<Channel>
  >,
  /**
   * / List the caller's favorite channels. Requires a signed-in caller.
   */
  'listFavorites' : ActorMethod<[], Array<Channel>>,
  /**
   * / List the programs scheduled on a channel.
   */
  'listPrograms' : ActorMethod<[ChannelId], Array<Program>>,
  /**
   * / Remove a channel from the caller's favorites. Requires a signed-in caller.
   */
  'removeFavorite' : ActorMethod<[ChannelId], undefined>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];