/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ChannelId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Category = IDL.Variant({
  'music' : IDL.Null,
  'documentary' : IDL.Null,
  'kids' : IDL.Null,
  'news' : IDL.Null,
  'sports' : IDL.Null,
  'movies' : IDL.Null,
});
export const Channel = IDL.Record({
  'id' : ChannelId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isLive' : IDL.Bool,
  'logoUrl' : IDL.Text,
  'category' : Category,
  'streamUrl' : IDL.Text,
  'popularity' : IDL.Nat,
});
export const ProgramId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Program = IDL.Record({
  'id' : ProgramId,
  'startTime' : Timestamp,
  'title' : IDL.Text,
  'channelId' : ChannelId,
  'endTime' : Timestamp,
  'description' : IDL.Text,
});
export const ChannelDetail = IDL.Record({
  'nowPlaying' : IDL.Opt(Program),
  'upNext' : IDL.Opt(Program),
  'channel' : Channel,
});
export const ChannelSort = IDL.Variant({
  'name' : IDL.Null,
  'popularity' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addFavorite' : IDL.Func([ChannelId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([ChannelId], [IDL.Opt(Channel)], ['query']),
  'getChannelDetail' : IDL.Func(
      [ChannelId],
      [IDL.Opt(ChannelDetail)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'listChannelsByCategory' : IDL.Func(
      [Category, ChannelSort],
      [IDL.Vec(Channel)],
      ['query'],
    ),
  'listFavorites' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'listPrograms' : IDL.Func([ChannelId], [IDL.Vec(Program)], ['query']),
  'removeFavorite' : IDL.Func([ChannelId], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ChannelId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Category = IDL.Variant({
    'music' : IDL.Null,
    'documentary' : IDL.Null,
    'kids' : IDL.Null,
    'news' : IDL.Null,
    'sports' : IDL.Null,
    'movies' : IDL.Null,
  });
  const Channel = IDL.Record({
    'id' : ChannelId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isLive' : IDL.Bool,
    'logoUrl' : IDL.Text,
    'category' : Category,
    'streamUrl' : IDL.Text,
    'popularity' : IDL.Nat,
  });
  const ProgramId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Program = IDL.Record({
    'id' : ProgramId,
    'startTime' : Timestamp,
    'title' : IDL.Text,
    'channelId' : ChannelId,
    'endTime' : Timestamp,
    'description' : IDL.Text,
  });
  const ChannelDetail = IDL.Record({
    'nowPlaying' : IDL.Opt(Program),
    'upNext' : IDL.Opt(Program),
    'channel' : Channel,
  });
  const ChannelSort = IDL.Variant({
    'name' : IDL.Null,
    'popularity' : IDL.Null,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addFavorite' : IDL.Func([ChannelId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([ChannelId], [IDL.Opt(Channel)], ['query']),
    'getChannelDetail' : IDL.Func(
        [ChannelId],
        [IDL.Opt(ChannelDetail)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'listChannelsByCategory' : IDL.Func(
        [Category, ChannelSort],
        [IDL.Vec(Channel)],
        ['query'],
      ),
    'listFavorites' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'listPrograms' : IDL.Func([ChannelId], [IDL.Vec(Program)], ['query']),
    'removeFavorite' : IDL.Func([ChannelId], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };